apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pokemon-fastapi
  template:
    metadata:
      labels:
        app: pokemon-fastapi
    spec:
      containers:
        - name: pokemon-fastapi
          image: pokemon-fastapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pokemon-config
            - secretRef:
                name: postgres-secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: a-volume
              mountPath: /etc/configs
              readOnly: true
      volumes:
      - name: a-volume
        configMap:
          name: pokemon-config
          items:
          - key: example.properties
            path: example.properties

        