apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-fastapi
spec:
  replicas: 3

  # Select pods with this label
  selector:
    matchLabels:
      app: pokemon-fastapi

  # Pod template
  template:
    metadata:
      labels:
        app: pokemon-fastapi
    
    # Container specs
    spec:
      containers:
        - name: pokemon-fastapi
          image: pokemon-fastapi:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000

          envFrom:
            - configMapRef:
                name: pokemon-config
            - secretRef:
                name: postgres-secret
          
          resources:
            # Reserve this amount of resources on a Pod for the app to run
            requests:
              cpu: "100m" # millicores (1/10 of a core)
              memory: "128Mi" # Mebibyte
            # Ceiling of resources for this container to use
            limits:
              cpu: "500m"
              memory: "256Mi"
          
          volumeMounts:
            - name: a-volume
              mountPath: /etc/configs
              readOnly: true

          # Restarts the container if it fails to start up
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 12

          # Readiness to receive traffic, remove from service endpoint if not
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 2

          # Live check, if not then restart
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 3
            
      # Mount Volume
      volumes:
      - name: a-volume
        configMap:
          name: pokemon-config
          items:
          - key: example.properties # Key in ConfigMap
            path: example.properties # Path to save values in

        