apiVersion: v1
kind: ConfigMap
metadata:
  name: pokemon-config
data:
  POKEMON_API_URL: "https://pokeapi.co/api/v2"
  POKEMON_CONCURRENCY: "25"
  POKEMON_RATE_LIMIT: "100"
  POKEMON_RATE_SECONDS: "3"
  POKEMON_TIMEOUT: "10"

  example.properties: |
    property_one=10
    property_two=a_string
    property_three-4.0