FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY pokemon_api ./pokemon_api

EXPOSE 8000

CMD ["python", "-m", "uvicorn", "pokemon_api.app:app", "--host", "0.0.0.0", "--port", "8000"]